version: '3'

services:
  web:
    build: .
    command: bash /entrypoint.sh
    volumes:
      - .:/app
      - ./logs:/app/logs
    ports:
      - "8000:8000"
    depends_on:
      - redis
      - db
    env_file:
      - .env
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
    env_file:
      - .env
  db:
    image: postgres:13
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: